# Generated by Django 5.1.2 on 2026-03-15 16:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=100, null=True)),
                ("lastname", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "companyname",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("osobafizyczna", "Osoba fizyczna"),
                            ("firma", "Firma"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pesel",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        validators=[django.core.validators.RegexValidator("^\\d{11}$")],
                    ),
                ),
                (
                    "nip",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{10,13}$")
                        ],
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "addressstreet",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "addresscity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("addresszip", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    models.CharField(blank=True, default="Polska", max_length=100),
                ),
                ("createdat", models.DateTimeField(auto_now_add=True)),
                ("updatedat", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "CLIENTS",
            },
        ),
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                (
                    "barnumber",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("activeflag", models.BooleanField(default=True)),
                (
                    "defaultrate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("createdat", models.DateTimeField(auto_now_add=True)),
                ("updatedat", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "LAWYERS",
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("casenumber", models.CharField(max_length=50, unique=True)),
                (
                    "courtcasenumber",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "casetype",
                    models.CharField(
                        choices=[
                            ("cywilna", "Cywilna"),
                            ("karna", "Karna"),
                            ("gospodarcza", "Gospodarcza"),
                            ("administracyjna", "Administracyjna"),
                            ("rodzinna", "Rodzinna"),
                            ("pracownicza", "Pracownicza"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nowa", "Nowa"),
                            ("w_toku", "W toku"),
                            ("zawieszona", "Zawieszona"),
                            ("zakończona", "Zakończona"),
                            ("archiwalna", "Archiwalna"),
                        ],
                        default="nowa",
                        max_length=20,
                    ),
                ),
                (
                    "casepriority",
                    models.CharField(
                        choices=[
                            ("niska", "Niska"),
                            ("normalna", "Normalna"),
                            ("wysoka", "Wysoka"),
                            ("pilna", "Pilna"),
                        ],
                        default="normalna",
                        max_length=10,
                    ),
                ),
                ("openedat", models.DateTimeField(blank=True, null=True)),
                ("closedat", models.DateTimeField(blank=True, null=True)),
                ("createdat", models.DateTimeField(auto_now_add=True)),
                ("updatedat", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        db_column="clientid",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="szkp.client",
                    ),
                ),
            ],
            options={
                "db_table": "CASES",
            },
        ),
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "documenttype",
                    models.CharField(
                        choices=[
                            ("pozew", "Pozew"),
                            ("odpowiedz", "Odpowiedź"),
                            ("pismo_sadowe", "Pismo sądowe"),
                            ("notatka", "Notatka"),
                            ("umowa", "Umowa"),
                            ("dowod", "Dowód"),
                            ("wyrok", "Wyrok"),
                            ("ugoda", "Ugoda"),
                        ],
                        max_length=30,
                    ),
                ),
                ("isinternal", models.BooleanField(default=False)),
                ("createdat", models.DateTimeField(auto_now_add=True)),
                ("updatedat", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        db_column="caseid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="szkp.case",
                    ),
                ),
            ],
            options={
                "db_table": "DOCUMENTS",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoicenumber", models.CharField(max_length=50, unique=True)),
                ("currency", models.CharField(default="PLN", max_length=3)),
                (
                    "vatrate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.23"), max_digits=5
                    ),
                ),
                (
                    "netamount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "grossamount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("wystawiona", "Wystawiona"),
                            ("opłacona", "Opłacona"),
                            ("przeterminowana", "Przeterminowana"),
                        ],
                        default="wystawiona",
                        max_length=20,
                    ),
                ),
                ("issuedate", models.DateField()),
                ("duedate", models.DateField()),
                ("paidat", models.DateTimeField(blank=True, null=True)),
                ("createdat", models.DateTimeField(auto_now_add=True)),
                ("updatedat", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_column="caseid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="szkp.case",
                    ),
                ),
            ],
            options={
                "db_table": "INVOICES",
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("versionnumber", models.IntegerField()),
                ("filepath", models.CharField(max_length=500)),
                ("createdat", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        db_column="documentid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="szkp.documents",
                    ),
                ),
                (
                    "createdbylawyer",
                    models.ForeignKey(
                        db_column="createdbylawyerid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="szkp.lawyer",
                    ),
                ),
            ],
            options={
                "db_table": "DOCUMENTVERSIONS",
            },
        ),
        migrations.CreateModel(
            name="CourtHearing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("courtname", models.CharField(max_length=200)),
                ("courtroom", models.CharField(blank=True, max_length=50)),
                (
                    "hearingtype",
                    models.CharField(
                        choices=[
                            ("rozprawa", "Rozprawa"),
                            ("posiedzenie", "Posiedzenie"),
                            ("mediacja", "Mediacja"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduledat", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planowany", "Planowany"),
                            ("odbyty", "Odbyty"),
                            ("odroczony", "Odroczony"),
                            ("odwołany", "Odwołany"),
                        ],
                        default="planowany",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reminderminutesbefore", models.IntegerField(default=1440)),
                ("remindersentat", models.DateTimeField(blank=True, null=True)),
                ("createdat", models.DateTimeField(auto_now_add=True)),
                ("updatedat", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        db_column="caseid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="szkp.case",
                    ),
                ),
                (
                    "responsiblelawyer",
                    models.ForeignKey(
                        blank=True,
                        db_column="responsiblawyerid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="szkp.lawyer",
                    ),
                ),
            ],
            options={
                "db_table": "COURTHEARINGS",
            },
        ),
        migrations.CreateModel(
            name="CaseLawyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("prowadzacy", "Prowadzący"),
                            ("asystent", "Asystent"),
                            ("doradca", "Doradca"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assignedat", models.DateTimeField(auto_now_add=True)),
                ("unassignedat", models.DateTimeField(blank=True, null=True)),
                ("responsibleflag", models.BooleanField(default=False)),
                (
                    "case",
                    models.ForeignKey(
                        db_column="caseid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="szkp.case",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        db_column="lawyerid",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="szkp.lawyer",
                    ),
                ),
            ],
            options={
                "db_table": "CASELAWYERS",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("niska", "Niska"),
                            ("normalna", "Normalna"),
                            ("wysoka", "Wysoka"),
                            ("pilna", "Pilna"),
                        ],
                        default="normalna",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nowe", "Nowe"),
                            ("w_toku", "W toku"),
                            ("zawieszone", "Zawieszone"),
                            ("zakończone", "Zakończone"),
                            ("archiwalne", "Archiwalne"),
                        ],
                        default="nowe",
                        max_length=20,
                    ),
                ),
                ("duedate", models.DateTimeField(blank=True, null=True)),
                ("completedat", models.DateTimeField(blank=True, null=True)),
                ("createdat", models.DateTimeField(auto_now_add=True)),
                ("updatedat", models.DateTimeField(auto_now=True)),
                (
                    "assignedlawyer",
                    models.ForeignKey(
                        db_column="assignedlawyerid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to="szkp.lawyer",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_column="caseid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="szkp.case",
                    ),
                ),
                (
                    "createdby",
                    models.ForeignKey(
                        db_column="createdby",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to="szkp.lawyer",
                    ),
                ),
                (
                    "parenttask",
                    models.ForeignKey(
                        blank=True,
                        db_column="parenttaskid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="szkp.task",
                    ),
                ),
            ],
            options={
                "db_table": "TASKS",
            },
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["courtcasenumber"], name="idx_cases_courtcase"),
        ),
        migrations.AlterUniqueTogether(
            name="caselawyer",
            unique_together={("case", "lawyer")},
        ),
    ]
