# Generated by Django 5.1.2 on 2026-03-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("szkp", "0002_remove_case_idx_cases_courtcase_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Documents",
            new_name="Document",
        ),
    ]
