# Generated by Django 5.1.2 on 2026-03-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("szkp", "0003_rename_documents_document"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="companyname",
            new_name="company_name",
        ),
    ]
