# Generated by Django 5.1.2 on 2026-05-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("szkp", "0004_rename_companyname_client_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="courthearing",
            name="judge_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
