# Generated by Django 5.1.2 on 2026-06-11 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("szkp", "0006_lawyer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="nip",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[django.core.validators.RegexValidator("^\\d{10}$")],
            ),
        ),
    ]
