# Generated by Django 5.1.2 on 2026-06-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("szkp", "0007_alter_client_nip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("nowe", "Nowe"),
                    ("w_toku", "W toku"),
                    ("zawieszone", "Zawieszone"),
                    ("zakończone", "Zakończone"),
                ],
                default="nowe",
                max_length=20,
            ),
        ),
    ]
